#!/usr/bin/ruby
require 'rubygems'
require 'fog'
require 'sequel'

config = File.open( 'servers.yml' ) { |yf| YAML::load( yf ) }

connection = Fog::AWS::EC2.new(
   :aws_access_key_id => @aws_access_key_id,
   :aws_secret_access_key => @aws_secret_access_key 
)
=begin
DB = Sequel.mysql(:host=>'localhost', :user=>'cacti', :password=>'FsBrqVGAz51Q', :database=>'cacti')

instance_list = connection.servers.all

instance_datas = instance_list.collect { |instance| { :private_ip_address => instance.private_ip_address, :tags => instance.tags } }
# puts instance_data.inspect

instance_datas.each do |instance_data|
 #DB.fetch("select id from host where hostname='#{instance_data[:private_ip_address]}' limit 1") do |row|
   # add the new device
   %x(/usr/bin/php /usr/share/cacti/cli/add_device.php --description="#{instance_data[:tags]['Name']}" --ip="#{instance_data[:private_ip_address]}" --template="3" --avail="ping" --ping_method="icmp" --ping_retries="2" --version="1" --community="public" --port="161" --timeout="500")
   
   # grab the id of the host from the database
   DB.fetch("select id from host where hostname='#{instance_data[:private_ip_address]}' limit 1") do |row|
     @host_id = row[:id]
   end
 
   # add the new device to the client's tree
   %x(/usr/bin/php /usr/share/cacti/cli/add_tree.php --type="node" --node-type="host" --tree-id="#{@tree_id}" --host-id="#{@host_id}")
 
   # get some stock graphs up and running
   @graph_template_ids.each do |graph_template_id|
     puts "/usr/bin/php /usr/share/cacti/cli/add_graphs.php --graph-type=\"cg\" --graph-template-id=\"#{graph_template_id}\" --host-id=\"#{@host_id}\""
     %x(/usr/bin/php /usr/share/cacti/cli/add_graphs.php --graph-type="cg" --graph-template-id="#{graph_template_id}" --host-id="#{@host_id}")
   end
 
   # add permissions to the client's user
   %x(/usr/bin/php /usr/share/cacti/cli/add_perms.php --user-id="#{@user_id}" --item-type="host" --item-id="#{@host_id}")
 #end
end
=end
