#!/usr/bin/ruby
require 'rubygems'
require 'fog'

config = File.open( 'accounts.yml' ) { |yf| YAML::load( yf ) }

accounts = ARGV[1].nil? ? config : config[ARGV[1]]

active_requests = [] #not really sure what to do with these but I'll keep them around.

accounts.each do |key, account|
	instance = Fog::Compute.new(
			:provider           => 'AWS',
			:aws_access_key_id  =>  account['aws_access_key_id'],
			:aws_secret_access_key =>  account['aws_secret_access_key'] 
	)
	instance.volumes.each do |volume|
		puts "requesting snapshot for #{key}[#{volume.id}]"
		active_requests = instance.create_snapshot volume.id, "#{key} - #{Time.now}"
	end
end
